import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { scanForGgufs } from '../backend/GgufScanner';
import { deriveModelSuggestion } from '../backend/ModelHeuristics';
import type { GgufCandidate } from '../backend/GgufScanner';
import type { ModelSuggestion } from '../backend/ModelHeuristics';

interface StarterConfigOpts {
  ggufPath: string;
  modelName: string;
  binary: string;
  suggestion: ModelSuggestion;
}

function generateStarterConfig(opts: StarterConfigOpts): string {
  return `# Forge config.yaml — auto-generated by first-run wizard
models:
  - name: ${opts.modelName}
    gguf_path: "${opts.ggufPath}"
    num_ctx: ${opts.suggestion.numCtx}
    n_batch: ${opts.suggestion.nBatch}
    flash_attn: ${opts.suggestion.flashAttn}

active_model: ${opts.modelName}

llama_server:
  binary: "${opts.binary}"
  n_gpu_layers: -1
  flash_attn_default: true
  default_num_ctx: ${opts.suggestion.numCtx}
`;
}

/**
 * Shown when no config.yaml exists. Guides user through:
 * 1. Scanning for GGUFs
 * 2. Picking llama-server binary
 * 3. Writing a starter config.yaml
 *
 * Returns true if config was written, false if user skipped or no models found.
 */
export async function runFirstRunWizard(context: vscode.ExtensionContext): Promise<boolean> {
  // Step 1: Offer to scan
  const scan = await vscode.window.showInformationMessage(
    'Forge: No config.yaml found. Scan for GGUF models?',
    { modal: false },
    'Scan',
    'Skip',
  );

  let candidates: GgufCandidate[] = [];
  if (scan === 'Scan') {
    await vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: 'Forge: Scanning for GGUF models…',
      },
      async () => {
        candidates = await scanForGgufs();
      },
    );
    if (candidates.length === 0) {
      await vscode.window.showWarningMessage(
        'No GGUF files found. Configure config.yaml manually.',
      );
      return false;
    }
  } else {
    return false;
  }

  // Step 2: pick model (show up to 10)
  const items = candidates.slice(0, 10).map((c) => ({
    label: c.modelName,
    description: `${(c.sizeBytes / 1e9).toFixed(1)} GB — ${c.familyHint}`,
    path: c.ggufPath,
  }));

  const picked = await vscode.window.showQuickPick(items, {
    placeHolder: 'Select a GGUF model',
    title: 'Forge: Pick your model',
  });
  if (!picked) return false;

  // Step 3: pick llama-server binary
  const binResult = await vscode.window.showInputBox({
    prompt: 'Path to llama-server binary (leave blank to search PATH)',
    placeHolder: '/usr/local/bin/llama-server or C:\\llama.cpp\\llama-server.exe',
    ignoreFocusOut: true,
  });

  const selectedCandidate = candidates.find((c) => c.ggufPath === picked.path);
  if (!selectedCandidate) return false;

  const suggestion = deriveModelSuggestion(selectedCandidate);

  // Step 4: write config.yaml into workspace .forge/ or home .forge/
  const configDir = path.join(
    vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? os.homedir(),
    '.forge',
  );
  fs.mkdirSync(configDir, { recursive: true });
  const configPath = path.join(configDir, 'config.yaml');

  const yaml = generateStarterConfig({
    ggufPath: picked.path,
    modelName: suggestion.suggestedName,
    binary: binResult || 'llama-server',
    suggestion,
  });

  fs.writeFileSync(configPath, yaml, 'utf8');

  const choice = await vscode.window.showInformationMessage(
    `Forge: config.yaml written to ${configPath}. Reload window to start.`,
    'Reload',
  );
  if (choice === 'Reload') {
    void vscode.commands.executeCommand('workbench.action.reloadWindow');
  }

  await context.globalState.update('forge.firstRun.shown', true);
  return true;
}
