import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { scanForGgufs } from '../backend/GgufScanner';
import { deriveModelSuggestion } from '../backend/ModelHeuristics';
import type { GgufCandidate } from '../backend/GgufScanner';
import type { ModelSuggestion } from '../backend/ModelHeuristics';

interface StarterConfigOpts {
  ggufPath: string;
  modelName: string;
  binary: string;
  suggestion: ModelSuggestion;
}

function generateLlamaCppConfig(opts: StarterConfigOpts): string {
  return `# Forge config.yaml — auto-generated by first-run wizard
models:
  - name: ${opts.modelName}
    gguf_path: "${opts.ggufPath}"
    num_ctx: ${opts.suggestion.numCtx}
    n_batch: ${opts.suggestion.nBatch}
    flash_attn: ${opts.suggestion.flashAttn}

active_model: ${opts.modelName}

llama_server:
  binary: "${opts.binary}"
  n_gpu_layers: -1
  flash_attn_default: true
  default_num_ctx: ${opts.suggestion.numCtx}
`;
}

function generateOllamaConfig(endpoint: string, modelName: string): string {
  return `# Forge config.yaml — auto-generated by first-run wizard
bridge_mode: true

models:
  - name: ${modelName}
    provider: ollama
    endpoint: "${endpoint}"
    num_ctx: 32768

active_model: ${modelName}
`;
}

function generateBridgeConfig(baseUrl: string, modelName: string): string {
  return `# Forge config.yaml — auto-generated by first-run wizard
bridge_mode: true

models:
  - name: ${modelName}
    provider: ollama
    endpoint: "${baseUrl}"
    num_ctx: 32768

active_model: ${modelName}
`;
}

function writeConfigAndReload(configDir: string, yaml: string): void {
  fs.mkdirSync(configDir, { recursive: true });
  const configPath = path.join(configDir, 'config.yaml');
  fs.writeFileSync(configPath, yaml, 'utf8');
}

function targetConfigDir(context: vscode.ExtensionContext): string {
  // Write to global storage so the config is found in any workspace.
  // Per-workspace override: create .forge/config.yaml in the workspace root.
  return context.globalStorageUri.fsPath;
}

async function promptReload(configPath: string): Promise<boolean> {
  const choice = await vscode.window.showInformationMessage(
    `Forge: config.yaml written to ${configPath}. Reload window to start.`,
    'Reload',
  );
  if (choice === 'Reload') {
    void vscode.commands.executeCommand('workbench.action.reloadWindow');
    return true;
  }
  return false;
}

// ── llama.cpp flow ────────────────────────────────────────────────────────────

async function runLlamaCppFlow(context: vscode.ExtensionContext): Promise<boolean> {
  const scan = await vscode.window.showInformationMessage(
    'Forge: Scan for GGUF model files?',
    { modal: false },
    'Scan',
    'Skip',
  );

  let candidates: GgufCandidate[] = [];
  if (scan === 'Scan') {
    await vscode.window.withProgress(
      { location: vscode.ProgressLocation.Notification, title: 'Forge: Scanning for GGUF models…' },
      async () => { candidates = await scanForGgufs(); },
    );
    if (candidates.length === 0) {
      await vscode.window.showWarningMessage('No GGUF files found. Configure config.yaml manually.');
      return false;
    }
  } else {
    return false;
  }

  const items = candidates.slice(0, 10).map((c) => ({
    label: c.modelName,
    description: `${(c.sizeBytes / 1e9).toFixed(1)} GB — ${c.familyHint}`,
    path: c.ggufPath,
  }));

  const picked = await vscode.window.showQuickPick(items, {
    placeHolder: 'Select a GGUF model',
    title: 'Forge: Pick your model',
  });
  if (!picked) return false;

  const binResult = await vscode.window.showInputBox({
    prompt: 'Path to llama-server binary (leave blank to search PATH)',
    placeHolder: '/usr/local/bin/llama-server or C:\\llama.cpp\\llama-server.exe',
    ignoreFocusOut: true,
  });

  const selectedCandidate = candidates.find((c) => c.ggufPath === picked.path);
  if (!selectedCandidate) return false;

  const suggestion = deriveModelSuggestion(selectedCandidate);
  const configDir = targetConfigDir(context);
  const yaml = generateLlamaCppConfig({
    ggufPath: picked.path,
    modelName: suggestion.suggestedName,
    binary: binResult || 'llama-server',
    suggestion,
  });

  writeConfigAndReload(configDir, yaml);
  await context.globalState.update('forge.firstRun.shown', true);
  await promptReload(path.join(configDir, 'config.yaml'));
  return true;
}

// ── Ollama flow ───────────────────────────────────────────────────────────────

async function fetchOllamaModels(endpoint: string): Promise<string[]> {
  const base = endpoint.replace(/\/$/, '').replace(/\/(v1|api)$/, '');
  const res = await fetch(`${base}/api/tags`, { signal: AbortSignal.timeout(5000) });
  if (!res.ok) return [];
  const data = await res.json() as { models?: { name: string }[] };
  return (data.models ?? []).map((m) => m.name).filter(Boolean);
}

async function runOllamaFlow(context: vscode.ExtensionContext): Promise<boolean> {
  const endpointInput = await vscode.window.showInputBox({
    title: 'Forge: Ollama endpoint',
    prompt: 'Ollama base URL',
    value: 'http://127.0.0.1:11434',
    ignoreFocusOut: true,
  });
  if (!endpointInput) return false;
  const endpoint = endpointInput.trim().replace(/\/$/, '');

  let modelName: string | undefined;
  let models: string[] = [];

  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: 'Forge: Fetching Ollama models…' },
    async () => { models = await fetchOllamaModels(endpoint).catch(() => []); },
  );

  if (models.length > 0) {
    const picked = await vscode.window.showQuickPick(
      models.map((m) => ({ label: m })),
      { title: 'Forge: Pick an Ollama model', placeHolder: 'Select model' },
    );
    modelName = picked?.label;
  }

  if (!modelName) {
    modelName = await vscode.window.showInputBox({
      title: 'Forge: Ollama model name',
      prompt: 'Enter exact model tag (e.g. gemma4:e4b)',
      placeHolder: 'gemma4:e4b',
      ignoreFocusOut: true,
    });
  }
  if (!modelName) return false;

  const configDir = targetConfigDir(context);
  writeConfigAndReload(configDir, generateOllamaConfig(endpoint, modelName));
  await context.globalState.update('forge.firstRun.shown', true);
  await promptReload(path.join(configDir, 'config.yaml'));
  return true;
}

// ── External bridge flow ──────────────────────────────────────────────────────

async function fetchBridgeModels(baseUrl: string): Promise<string[]> {
  const url = baseUrl.replace(/\/$/, '');
  const apiUrl = url.endsWith('/v1') ? `${url}/models` : `${url}/v1/models`;
  const res = await fetch(apiUrl, { signal: AbortSignal.timeout(5000) });
  if (!res.ok) return [];
  const data = await res.json() as { data?: { id: string }[] };
  return (data.data ?? []).map((m) => m.id).filter(Boolean);
}

async function runBridgeFlow(context: vscode.ExtensionContext): Promise<boolean> {
  const urlInput = await vscode.window.showInputBox({
    title: 'Forge: External bridge URL',
    prompt: 'Base URL of your OpenAI-compatible server',
    value: 'http://127.0.0.1:9099',
    ignoreFocusOut: true,
  });
  if (!urlInput) return false;
  const baseUrl = urlInput.trim().replace(/\/$/, '');

  let modelName: string | undefined;
  let models: string[] = [];

  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: 'Forge: Fetching models from bridge…' },
    async () => { models = await fetchBridgeModels(baseUrl).catch(() => []); },
  );

  if (models.length > 0) {
    const picked = await vscode.window.showQuickPick(
      models.map((m) => ({ label: m })),
      { title: 'Forge: Pick a model', placeHolder: 'Select model' },
    );
    modelName = picked?.label;
  }

  if (!modelName) {
    modelName = await vscode.window.showInputBox({
      title: 'Forge: Model name',
      prompt: 'Enter the model id as the server knows it',
      placeHolder: 'gemma4-e4b-it-ud-q8kxl',
      ignoreFocusOut: true,
    });
  }
  if (!modelName) return false;

  const configDir = targetConfigDir(context);
  writeConfigAndReload(configDir, generateBridgeConfig(baseUrl, modelName));
  await context.globalState.update('forge.firstRun.shown', true);
  await promptReload(path.join(configDir, 'config.yaml'));
  return true;
}

// ── Entry point ───────────────────────────────────────────────────────────────

/**
 * Shown when no config.yaml exists. Guides the user through backend selection
 * and writes a starter config.yaml to global storage (works across all workspaces).
 * Per-workspace override: create .forge/config.yaml in the workspace root.
 * Returns true if a config was written, false if the user cancelled.
 */
export async function runFirstRunWizard(context: vscode.ExtensionContext): Promise<boolean> {
  const backendPick = await vscode.window.showQuickPick(
    [
      {
        label: '$(server) llama.cpp',
        description: 'Run local GGUF files via llama-server',
        value: 'llamacpp',
      },
      {
        label: '$(hubot) Ollama',
        description: 'Connect to a running Ollama instance',
        value: 'ollama',
      },
      {
        label: '$(plug) External bridge',
        description: 'Connect to any running OpenAI-compatible server',
        value: 'bridge',
      },
    ],
    {
      title: 'Forge: How do you want to run models?',
      placeHolder: 'Select a backend',
      ignoreFocusOut: true,
    },
  );

  if (!backendPick) return false;

  if (backendPick.value === 'llamacpp') return runLlamaCppFlow(context);
  if (backendPick.value === 'ollama') return runOllamaFlow(context);
  return runBridgeFlow(context);
}
