import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { scanForGgufs } from '../backend/GgufScanner';
import { deriveModelSuggestion } from '../backend/ModelHeuristics';
import type { GgufCandidate } from '../backend/GgufScanner';
import type { ModelSuggestion } from '../backend/ModelHeuristics';

interface StarterModelOpts {
  ggufPath: string;
  modelName: string;
  suggestion: ModelSuggestion;
}

function generateLlamaCppConfig(models: StarterModelOpts[], binary: string): string {
  const entries = models
    .map(
      (opts) => `  - name: ${opts.modelName}
    gguf_path: "${opts.ggufPath}"
    spawn:
      num_ctx: ${opts.suggestion.numCtx}
      n_batch: ${opts.suggestion.nBatch}
      flash_attn: ${opts.suggestion.flashAttn}`,
    )
    .join('\n');
  return `# Forge config.yaml — auto-generated by first-run wizard
# F6 shape: per-model spawn-time facts live under "spawn:"; request-time roles
# (system_prompt / sampling / think) go under "profiles:" and are selected via
# active_model: <name>@<profile>. See config/config.example.yaml.
models:
${entries}

active_model: ${models[0]?.modelName}

llama_server:
  binary: "${binary}"
  n_gpu_layers: -1
  flash_attn_default: true
  default_num_ctx: ${models[0]?.suggestion.numCtx}

permissions:
  fs: { read: true, write: true, delete: false }
  net: { search: false, fetch: false }
  exec: { terminal: false, headless: false }
  git: { read: true, write: false }
`;
}

function generateOllamaConfig(endpoint: string, modelNames: string[]): string {
  const entries = modelNames
    .map(
      (modelName) => `  - name: ${modelName}
    provider: ollama
    endpoint: "${endpoint}"
    num_ctx: 32768`,
    )
    .join('\n');
  return `# Forge config.yaml — auto-generated by first-run wizard
models:
${entries}

active_model: ${modelNames[0]}

permissions:
  fs: { read: true, write: true, delete: false }
  net: { search: false, fetch: false }
  exec: { terminal: false, headless: false }
  git: { read: true, write: false }
`;
}

function writeConfig(configDir: string, yaml: string): string {
  fs.mkdirSync(configDir, { recursive: true });
  const configPath = path.join(configDir, 'config.yaml');
  fs.writeFileSync(configPath, yaml, 'utf8');
  return configPath;
}

function targetConfigDir(context: vscode.ExtensionContext): string {
  // Write to global storage so the config is found in any workspace.
  // Per-workspace override: create .forge/config.yaml in the workspace root.
  return context.globalStorageUri.fsPath;
}

async function promptGlobalPin(configPath: string): Promise<void> {
  const choice = await vscode.window.showInformationMessage(
    `Forge: Pin this config as the global config for all workspaces? (Sets forge.configFile in user settings)`,
    'Pin globally',
    'Skip',
  );
  if (choice === 'Pin globally') {
    await vscode.workspace
      .getConfiguration('forge')
      .update('configFile', configPath, vscode.ConfigurationTarget.Global);
  }
}

async function promptReload(configPath: string): Promise<boolean> {
  const choice = await vscode.window.showInformationMessage(
    `Forge: config.yaml written to ${configPath}. Reload window to start.`,
    'Reload',
  );
  if (choice === 'Reload') {
    void vscode.commands.executeCommand('workbench.action.reloadWindow');
    return true;
  }
  return false;
}

async function finishWizard(context: vscode.ExtensionContext, configPath: string): Promise<void> {
  await context.globalState.update('forge.firstRun.shown', true);
  await promptGlobalPin(configPath);
  await promptReload(configPath);
}

// ── llama.cpp flow ────────────────────────────────────────────────────────────

async function runLlamaCppFlow(context: vscode.ExtensionContext): Promise<boolean> {
  const scan = await vscode.window.showInformationMessage(
    'Forge: Scan for GGUF model files?',
    { modal: false },
    'Scan',
    'Skip',
  );

  let candidates: GgufCandidate[] = [];
  if (scan === 'Scan') {
    await vscode.window.withProgress(
      { location: vscode.ProgressLocation.Notification, title: 'Forge: Scanning for GGUF models…' },
      async () => {
        candidates = await scanForGgufs();
      },
    );
    if (candidates.length === 0) {
      const extraDir = await vscode.window.showInputBox({
        title: 'Forge: No GGUF files found',
        prompt:
          'Enter a directory path to search (e.g. D:\\models or /mnt/nas/models), or leave blank to skip',
        placeHolder: 'D:\\models',
        ignoreFocusOut: true,
      });
      if (extraDir?.trim()) {
        await vscode.window.withProgress(
          { location: vscode.ProgressLocation.Notification, title: 'Forge: Scanning…' },
          async () => {
            candidates = await scanForGgufs([extraDir.trim()]);
          },
        );
      }
      if (candidates.length === 0) {
        await vscode.window.showWarningMessage(
          'No GGUF files found. Configure config.yaml manually.',
        );
        return false;
      }
    }
  } else {
    return false;
  }

  const items = candidates.slice(0, 10).map((c) => ({
    label: c.modelName,
    description: `${(c.sizeBytes / 1e9).toFixed(1)} GB — ${c.familyHint}`,
    path: c.ggufPath,
  }));

  const picked = await vscode.window.showQuickPick(items, {
    canPickMany: true,
    placeHolder: 'Select one or more GGUF models',
    title: 'Forge: Pick your model',
  });
  if (!picked?.length) return false;

  const binResult = await vscode.window.showInputBox({
    prompt: 'Path to llama-server binary (leave blank to search PATH)',
    placeHolder: '/usr/local/bin/llama-server or C:\\llama.cpp\\llama-server.exe',
    ignoreFocusOut: true,
  });

  const selected = picked
    .map((item) => candidates.find((c) => c.ggufPath === item.path))
    .filter((candidate): candidate is GgufCandidate => candidate !== undefined);
  if (!selected.length) return false;
  const configDir = targetConfigDir(context);
  const yaml = generateLlamaCppConfig(
    selected.map((candidate) => {
      const suggestion = deriveModelSuggestion(candidate);
      return { ggufPath: candidate.ggufPath, modelName: suggestion.suggestedName, suggestion };
    }),
    binResult || 'llama-server',
  );

  const configPath = writeConfig(configDir, yaml);
  await finishWizard(context, configPath);
  return true;
}

// ── Ollama flow ───────────────────────────────────────────────────────────────

export async function fetchOllamaModels(endpoint: string): Promise<string[]> {
  const base = endpoint.replace(/\/$/, '').replace(/\/(v1|api)$/, '');
  const res = await fetch(`${base}/api/tags`, { signal: AbortSignal.timeout(5000) });
  if (!res.ok) return [];
  const data = (await res.json()) as { models?: { name: string }[] };
  return (data.models ?? []).map((m) => m.name).filter(Boolean);
}

async function runOllamaFlow(context: vscode.ExtensionContext): Promise<boolean> {
  const endpointInput = await vscode.window.showInputBox({
    title: 'Forge: Ollama endpoint',
    prompt: 'Ollama base URL',
    value: 'http://127.0.0.1:11434',
    ignoreFocusOut: true,
  });
  if (!endpointInput) return false;
  const endpoint = endpointInput.trim().replace(/\/$/, '');

  let modelNames: string[] = [];
  let models: string[] = [];

  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: 'Forge: Fetching Ollama models…' },
    async () => {
      models = await fetchOllamaModels(endpoint).catch(() => []);
    },
  );

  if (models.length > 0) {
    const picked = await vscode.window.showQuickPick(
      models.map((m) => ({ label: m })),
      {
        canPickMany: true,
        title: 'Forge: Pick Ollama models',
        placeHolder: 'Select one or more models',
      },
    );
    modelNames = picked?.map((item) => item.label) ?? [];
  }

  if (!modelNames.length) {
    const modelName = await vscode.window.showInputBox({
      title: 'Forge: Ollama model name',
      prompt: 'Enter exact model tag (e.g. gemma4:e4b)',
      placeHolder: 'gemma4:e4b',
      ignoreFocusOut: true,
    });
    if (modelName) modelNames = [modelName];
  }
  if (!modelNames.length) return false;

  const configDir = targetConfigDir(context);
  const configPath = writeConfig(configDir, generateOllamaConfig(endpoint, modelNames));
  await finishWizard(context, configPath);
  return true;
}

// ── Entry point ───────────────────────────────────────────────────────────────

/**
 * Shown when no config.yaml exists. Guides the user through backend selection
 * and writes a starter config.yaml to global storage (works across all workspaces).
 * Per-workspace override: create .forge/config.yaml in the workspace root.
 * Returns true if a config was written, false if the user cancelled.
 */
export async function runFirstRunWizard(context: vscode.ExtensionContext): Promise<boolean> {
  const backendPick = await vscode.window.showQuickPick(
    [
      {
        label: '$(server) llama.cpp',
        description: 'Run local GGUF files via llama-server',
        value: 'llamacpp',
      },
      {
        label: '$(hubot) Ollama',
        description: 'Connect to a running Ollama instance',
        value: 'ollama',
      },
    ],
    {
      title: 'Forge: How do you want to run models?',
      placeHolder: 'Select a backend',
      ignoreFocusOut: true,
    },
  );

  if (!backendPick) return false;

  if (backendPick.value === 'llamacpp') return runLlamaCppFlow(context);
  return runOllamaFlow(context);
}
